apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-native-pie
  description: a pie chart for react native
  annotations: []
spec:
  type: library
  lifecycle: deprecated
  domain: unknown
  system: unknown
  owner: unknown
relations: []
